Tidy up output

diff --git a/clearwater_config_manager/scripts/upload_fallback_ifcs_xml b/clearwater_config_manager/scripts/upload_fallback_ifcs_xml
--- a/clearwater_config_manager/scripts/upload_fallback_ifcs_xml
+++ b/clearwater_config_manager/scripts/upload_fallback_ifcs_xml
@@ -19,8 +19,8 @@ apply_fallback_ifcs=N
 # Check we can contact `etcd`
 if ! nc -z ${management_local_ip:-$local_ip} 4000
 then
-  echo "The Clearwater Configuration store (etcd) is not running"
-  echo "Please start it before uploading configuration"
+  echo "The Clearwater Configuration store (etcd) is not running."
+  echo "Please start it before uploading configuration."
   exit 2
 fi
 
@@ -30,7 +30,7 @@ fi
 # full, or some other error may have occured.
 if [[ ! -f $FILENAME ]]
 then
-    echo "No configuration file at $FILENAME, unable to upload"
+    echo "No configuration file at $FILENAME, unable to upload."
     exit 2
 fi
 
@@ -39,8 +39,8 @@ rc=$?
 
 # Check the return code and log if appropriate.
 if [ $rc != 0 ] ; then
-  echo The fallback iFC file is invalid - unable to upload >&2
-  cat /tmp/upload-fallback-ifcs-xml.stderr.$$              >&2
+  echo The fallback iFC sets file is invalid - unable to upload.     >&2
+  cat /tmp/upload-fallback-ifcs-xml.stderr.$$ | grep -v "Loaded URL" >&2
   rm -f /tmp/upload-fallback-ifcs-xml.stderr.$$ /tmp/upload-fallback-ifcs-xml.stdout.$$
   exit $rc
 fi
@@ -50,7 +50,7 @@ uploadsize=500000
 filesize=$(wc -c <"$FILENAME")
 if [[ $filesize -ge $uploadsize ]]
 then
-  echo "The configuration file at $FILENAME is too large to upload (max size is $uploadsize bytes)"
+  echo "The configuration file at $FILENAME is too large to upload (max size is $uploadsize bytes)."
   exit 2
 fi
 
diff --git a/clearwater_config_manager/scripts/validate_shared_ifcs_xml b/clearwater_config_manager/scripts/validate_shared_ifcs_xml
--- a/clearwater_config_manager/scripts/validate_shared_ifcs_xml
+++ b/clearwater_config_manager/scripts/validate_shared_ifcs_xml
@@ -16,7 +16,7 @@ SCHEMA=/usr/share/clearwater/clearwater-config-manager/scripts/config_validation
 # Check that the file to validate is present.
 if [[ ! -f $FILENAME ]]
 then
-    echo "No configuration file at $FILENAME, unable to validate"
+    echo "No configuration file at $FILENAME, unable to validate."
     exit 2
 fi
 
@@ -25,10 +25,10 @@ rc=$?
 
 # Check the return code and log if appropriate.
 if [ $rc != 0 ] ; then
-  echo The shared iFC sets configuration is invalid      >&2
-  cat /tmp/validate-shared-ifcs-xml.stderr.$$            >&2
+  echo The shared iFC sets file is invalid.                        >&2
+  cat /tmp/upload-shared-ifcs-xml.stderr.$$ | grep -v "Loaded URL" >&2
 else
-  echo The shared iFC sets configuration is valid
+  echo The shared iFC sets configuration is valid.
 fi
 rm -f /tmp/validate-shared-ifcs-xml.stderr.$$ /tmp/validate-shared-ifcs-xml.stdout.$$
 
